### ISSUE TITLE
Error during setup of component ziggonext

### ISSUE THREAD

**Issue by Diondk** [Sholofly/ZiggoNext#18]
Hi,

Since today the ziggonext integration stopped working. i am getting the following error after i restarted HA:

`2020-01-30 22:11:45 ERROR (MainThread) [homeassistant.setup] Error during setup of component ziggonext
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 174, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ziggonext/__init__.py", line 30, in setup
    api.initialize(_LOGGER)
  File "/usr/local/lib/python3.7/site-packages/ziggonext/ziggonext.py", line 115, in initialize
    self.get_session_and_token()
  File "/usr/local/lib/python3.7/site-packages/ziggonext/ziggonext.py", line 80, in get_session_and_token
    self.get_session()
  File "/usr/local/lib/python3.7/site-packages/ziggonext/ziggonext.py", line 76, in get_session
    raise ZiggoNextConnectionError("Oops")
ziggonext.exceptions.ZiggoNextConnectionError: Oops`

looks like something has broken down on the ziggo end?

Kind Regards,
Dion

**Comment by Diondk** [comment]
This morning after restarting HA again, it started working.
