### ISSUE TITLE
Restart pending in HACS

### ISSUE THREAD

**Issue by roybosch** [Sholofly/ZiggoNext#21]
Hi!

Today I tried to install the ziggonext integration with HACS. No matter how often I restart HomeAssistant, it keeps saying that a restart is pending:

![image](https://user-images.githubusercontent.com/45666392/74653083-c2de3a00-5187-11ea-9639-7db0dd47a0b6.png)

When I'm checking the configuration file, it gives an error: `Component error: ziggonext - Integration 'ziggonext' not found.`

My configuration file contains the following, as described (including the correct indents):

ziggonext:
  username: !secret ziggo_username
  password: !secret ziggo_password

Any help would be great! :)

**Comment by Jeffreyvanesch** [comment]
Yep, Same problem here:

`Tue Feb 25 2020 21:22:55 GMT+0100 (Central European Standard Time)
Error loading custom_components.ziggonext. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 389, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/ziggonext/__init__.py", line 14, in <module>
    from ziggonext import ZiggoNext
ModuleNotFoundError: No module named 'ziggonext'`

**Comment by Sholofly** [comment]
@roybosch Still not working?

**Comment by roybosch** [comment]
I just tried. No more problems, it works great now. Thank you!
