### ISSUE TITLE
No image and information after turning off -> on

### ISSUE THREAD

**Issue by mike9011** [Sholofly/ZiggoNext#23]
## The problem
Since ~ 2 days the mediaplayer doesn't update anymore when it's switched off and turned on again.
It only shows this:
![image](https://user-images.githubusercontent.com/18025163/75675860-559ece80-5c88-11ea-9aeb-5a69cd704c1a.png)

When i open the "Ziggo Go" app and send a command to the mediabox , it will update in Home Assistant:
![image](https://user-images.githubusercontent.com/18025163/75675979-9e568780-5c88-11ea-9079-79c7d6994058.png)

## Environment
Home Assistant version: 0.106.2
Ziggo Next: 0.1.7

## Traceback/Error logs
None

**Comment by mike9011** [comment]
# Error
Since today, the component doesn't work anymore. Rebooting doesn't solve the issue.

Logger: homeassistant.setup
First occured: 18:03:15 (1 occurences)
Last logged: 18:03:15

```
Error during setup of component ziggonext
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 174, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ziggonext/__init__.py", line 30, in setup
    api.initialize(_LOGGER)
  File "/usr/local/lib/python3.7/site-packages/ziggonext/ziggonext.py", line 122, in initialize
    self.get_session_and_token()
  File "/usr/local/lib/python3.7/site-packages/ziggonext/ziggonext.py", line 88, in get_session_and_token
    self._get_token()
  File "/usr/local/lib/python3.7/site-packages/ziggonext/ziggonext.py", line 115, in _get_token
    jsonResult = self._do_api_call(self.session, self._api_url_token)
  File "/usr/local/lib/python3.7/site-packages/ziggonext/ziggonext.py", line 111, in _do_api_call
    raise ZiggoNextConnectionError("API call failed: " + str(response.status_code))
ziggonext.exceptions.ZiggoNextConnectionError: API call failed: 403
```

**Comment by mike9011** [comment]
Found the issue! Did some requests manually in order to get the 'X-OESP-Token', these failed too.
Until i changed the uppercase letters in my username to lowercase, now it's working again!
