### ISSUE TITLE
Component not working with Home Assistant 0.107.6

### ISSUE THREAD

**Issue by netrene** [Sholofly/ZiggoNext#24]
Since Version Home Assistant 0.107.6 the feedback is not working anymore and I get the following error:

Update for media_player.upc_tv_box fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 476, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ziggonext/media_player.py", line 69, in update
    self.api.load_channels()
  File "/usr/local/lib/python3.7/site-packages/ziggonext/ziggonext.py", line 189, in load_channels
    station["images"][2]["url"],
IndexError: list index out of range

Maybe this can be fixed?

Thx
René

**Comment by netrene** [comment]
It started working again with 0.107.7. This can be closed.
