### ISSUE TITLE
Component error: ziggonext - Integration 'ziggonext' not found.

### ISSUE THREAD

**Issue by HansHM** [Sholofly/ZiggoNext#35]
Hello Sholofly,

I have tried the manual install and trough HACS, but bouth give a error Component error: ziggonext - Integration 'ziggonext' not found.

configuration.yaml
ziggonext:
  username: xxxxx
  password: xxxxxx       

arch | x86_64
-- | --
chassis | vm
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.12
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.56
python_version | 3.8.3
supervisor | 235
timezone | Europe/Amsterdam
version | 0.114.3
virtualenv | false

![2020-08-22 11_45_36-File editor - Home Assistant](https://user-images.githubusercontent.com/46351946/90953607-1d28c200-e46d-11ea-9a6f-04eb4b773831.png)

Log Details (ERROR)
Logger: homeassistant.loader
Source: custom_components/ziggonext/__init__.py:14
First occurred: 11:13:39 AM (2 occurrences)
Last logged: 11:33:20 AM

Error loading custom_components.ziggonext. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 504, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/ziggonext/__init__.py", line 14, in <module>
    from ziggonext import ZiggoNext
ModuleNotFoundError: No module named 'ziggonext'

**Comment by LKonijn** [comment]
I got the same error, what did I miss?

**Comment by Sholofly** [comment]
It looks like it didn't install the package properly. A simple reboot should do the trick.

**Comment by HA-Peet** [comment]
Same here, reboot won't do the trick

**Comment by Sholofly** [comment]
How do you install the component?

**Comment by HA-Peet** [comment]
Installed it manually. All files to custom_components/ziggonext and the ziggonext user/pass in configuration.yaml

![image](https://user-images.githubusercontent.com/80528931/115136868-e8cccc00-a022-11eb-833f-7924c03852a4.png)
