### ISSUE TITLE
HA 0.116 ZiggoNextBox object has no attribute '_change_callback'

### ISSUE THREAD

**Issue by Veldkornet** [Sholofly/ZiggoNext#40]
I receive the following error after updating to HA 0.116

```
2020-10-07 19:25:46 ERROR (Thread-3) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3452, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2936, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3216, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3444, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 118, in _on_mqtt_client_message
    self.settop_boxes[deviceId]._update_settopbox_state(jsonPayload)
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonextbox.py", line 105, in _update_settopbox_state
    if self._change_callback:
AttributeError: 'ZiggoNextBox' object has no attribute '_change_callback'
```

**System:**
```
arch | aarch64
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.13
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v8
python_version | 3.8.5
supervisor | 247
timezone | Europe/Amsterdam
version | 0.116.0
virtualenv | false
```

**Comment by Sholofly** [comment]
Thanks for submitting. I have the same issue. I'm on it, but I don't expect
a fix today ...

Op wo 7 okt. 2020 om 20:11 schreef Veldkornet <notifications@github.com>:

**Comment by Sholofly** [comment]
Please update ziggonext to v0.2.0 Should be solved. Please report your findings!
