### ISSUE TITLE
BE version telenet

### ISSUE THREAD

**Issue by mikyD84** [Sholofly/ZiggoNext#51]
when i install the component, i get the error that te credentials are not correct, but on the site (telenettv.be) i can logon and control the devices, 

any sugestions? 

`Logger: homeassistant.setup
Source: custom_components/ziggonext/__init__.py:30
First occurred: 22:02:35 (1 occurrences)
Last logged: 22:02:35

Error during setup of component ziggonext
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ziggonext/__init__.py", line 30, in setup
    api.initialize(_LOGGER)
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 156, in initialize
    self.get_session_and_token()
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 78, in get_session_and_token
    self.get_session()
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 66, in get_session
    if status[0]['code'] == 'invalidCredentials':
KeyError: 0`

thnx

**Comment by Sholofly** [comment]
Please update the component and try again.

**Comment by mikyD84** [comment]
thnx all works fine!!!
