### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable when Videoland started

### ISSUE THREAD

**Issue by Polderdijk** [Sholofly/ZiggoNext#52]
When starting Videoland, the component stop working with the following error in the logfile:

Logger: root
Source: /usr/src/homeassistant/homeassistant/bootstrap.py:318
First occurred: 16:51:00 (1 occurrences)
Last logged: 16:51:00
Uncaught thread exception

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3452, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2936, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3216, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3444, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 120, in _on_mqtt_client_message
    self.settop_boxes[deviceId].update_settop_box(jsonPayload)
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonextbox.py", line 187, in update_settop_box
    self.info.setTitle(self._get_listing_title(listing))
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonextbox.py", line 223, in _get_listing_title
    return listing_content["program"]["title"]
TypeError: 'NoneType' object is not subscriptable

**Comment by geertsmichael** [comment]
I fixed this one I believe, can you check again on the latest version?

**Comment by Polderdijk** [comment]
> 
> 
> I fixed this one I believe, can you check again on the latest version?

I can confirm this update solved this problem! Many thanks and keep up the good work!
