### ISSUE TITLE
Opnames telenet box niet werk 

### ISSUE THREAD

**Issue by jrspowers** [Sholofly/ZiggoNext#56]
Hallo 

Ik heb alles ingevuld zo als het moet ? alles werk de media player met foto weergaven en de functie zender en aan/uit werk  ook almaal ? het is alleen de opnames die het niet doen ik kan de opnames niet open in de media ? dan krijg de fout bij bladeren door media unknown erro ? Het zouw fijn moest het opgelost geraak merci alvast ! ![C573A84A-D654-4ADF-B5B4-EB6B9EFA3774](https://user-images.githubusercontent.com/60328474/101377231-da6ee680-38b1-11eb-8f0e-265489c97fe3.png)

**Comment by Sholofly** [comment]
@geertsmichael Would you mind to take a look? Can't figure out the problem since i don't have a Telenet Box.

**Comment by geertsmichael** [comment]
@jrspowers zou je het deel in de log file kunnen delen dat de fout voor ziggonext toont. Die details heb ik nodig om te bepalen waardoor het fout gaat.

**Comment by jrspowers** [comment]
@geertsmichael dit is alles wat ik vind in de log wat op een fout kan lijken ?
 File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 18, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1066, in websocket_browse_media
    payload = await player.async_browse_media(media_content_type, media_content_id)
  File "/config/custom_components/ziggonext/media_player.py", line 303, in async_browse_media
    self._recordings = await self.hass.async_add_executor_job(self.api.get_recordings)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 400, in get_recordings
    json_result = self._do_api_call(self._api_url_recordings)
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 238, in _do_api_call
    self.get_session()
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 92, in get_session
    if status[0]['code'] == 'invalidCredentials':
merci alvast !

**Comment by geertsmichael** [comment]
Ik heb gevonden waar het aan ligt. Ik probeer zo snel mogelijk de fix uit.

**Comment by jrspowers** [comment]
@geertsmichael dat is top laat maar weten als het inorden is merci alvast !

**Comment by geertsmichael** [comment]
Versie 0.7.4 zou beschikbaar zijn waarin het probleem is opgelost. 
Kan je dat eens proberen @jrspowers ?

**Comment by jrspowers** [comment]
ik ben hem juist aan installeren en heropstart aan doen laat u zo weten @geertsmichael

**Comment by jrspowers** [comment]
nog altijd de zelfde fout @geertsmichael

**Comment by jrspowers** [comment]
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/ziggonext/media_player.py:303
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 23:10:58 (4 occurrences)
Last logged: 23:12:12

[139794917259632] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 18, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1066, in websocket_browse_media
    payload = await player.async_browse_media(media_content_type, media_content_id)
  File "/config/custom_components/ziggonext/media_player.py", line 303, in async_browse_media
    self._recordings = await self.hass.async_add_executor_job(self.api.get_recordings)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 406, in get_recordings
    results.append(self._get_single_recording(recording))
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 415, in _get_single_recording
    recording = ZiggoRecordingSingle(payload["recordingId"], payload["title"], payload["images"][0]["url"])
IndexError: list index out of range

hier de fout @geertsmichael hopelijk vind u het ?

**Comment by geertsmichael** [comment]
Dit is een andere fout. Je hebt vermoedelijk een opname zonder afbeelding. Ik heb de fix al, maar test hem morgen.

**Comment by jrspowers** [comment]
ja dat klop staan wel tussen kan ik zelf niks aan doen he kiest de opnamen zelf voor en top laat maar weten dan test ik hem als ik wakker ben merci alvast @geertsmichael

**Comment by geertsmichael** [comment]
Kan je de component updaten naar versie 0.7.5 en opnieuw proberen?

**Comment by jrspowers** [comment]
Hallo @geertsmichael ik heb de 0.7.5 geïnstalleerd maar deze heeft het probleem nog niet opgelost ik kan nog steed geen opnames open ik krijg de zelf fout als hier voor de unknown erro dus snap het niet in de logs staat allen dit 

Logger: homeassistant.components.media_player
Source: /usr/local/lib/python3.8/asyncio/events.py:81 
Integration: Mediaspeler (documentation, issues) 
First occurred: 12:28:18 (1 occurrences) 
Last logged: 12:28:18

Setup of media_player platform ziggonext is taking over 10 seconds.

Merci alvast

**Comment by jrspowers** [comment]
@geertsmichael hallo merci voor het fixen van deze probleem het werk almaal nu heel goed dus nog maal bedankt
