### ISSUE TITLE
KeyError: 'location" during setup (Telenet)

### ISSUE THREAD

**Issue by ArnoutVerbeken** [Sholofly/ZiggoNext#61]
Hello,

I tried to get this integration working but it seems it does not work.

Everything is up to date on HASS level.
In my configuration.yaml I have this:

```
ziggonext:
  username: user
  password: !secret telenetpasswd
  country_code: 'be-nl'
```

```
2021-01-29 13:09:26 ERROR (MainThread) [homeassistant.setup] Error during setup of component ziggonext
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 145, in get_be_session
    url = response.headers["Location"]
  File "/usr/local/lib/python3.8/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ziggonext/__init__.py", line 30, in setup
    api.connect(_LOGGER)
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 256, in connect
    self.get_session_and_token()
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 184, in get_session_and_token
    self.get_session()
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 82, in get_session
    self.get_be_session()
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 166, in get_be_session
    raise ZiggoNextConnectionError("Unknown connection failure")
ziggonext.exceptions.ZiggoNextConnectionError: Unknown connection failure
```

As far as I can see, everything is setup correctly.

My Telenet Decoder is the following type:  HD DigiCorder (AD2100)

Do you know what can be wrong?

**Comment by Sholofly** [comment]
Hi @ArnoutVerbeken This component is only suitable for the Telenet TV-box, not for the other decoders. They use a different communication and are therefore not supported. I'm sorry!
