### ISSUE TITLE
Uncaught thread exception

### ISSUE THREAD

**Issue by golles** [Sholofly/ZiggoNext#67]
Hi, yesterday I updated HA to 2021.4 and while reviewing all the logs I noticed this one.
I've got your master branch checked out.

```text
2021-04-08 12:10:30 ERROR (Thread-5) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3452, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2936, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3216, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3444, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 234, in _on_mqtt_client_message
    self.settop_boxes[deviceId].update_settop_box(jsonPayload)
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonextbox.py", line 189, in update_settop_box
    if not "channelId" in stateSource:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by Sholofly** [comment]
Hi @golles , Thanks for your report. Please update the component to fix this ussue :)

**Comment by golles** [comment]
Hi @Sholofly I got the same stack trace but now with a KeyError. I didn't want to open a new ticket for this, as it's the same issue, can you reopen this issue for me?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3452, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2936, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3216, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3444, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 234, in _on_mqtt_client_message
    self.settop_boxes[deviceId].update_settop_box(jsonPayload)
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonextbox.py", line 143, in update_settop_box
    channel = self.channels[channel_id]
KeyError: 'NL_000197_019504'
```

**Comment by Sholofly** [comment]
Hi and thank you for your response. Actually it's a different error.

Please open a new issue for this. Helps me keeping track..

Op za 10 apr. 2021 00:38 schreef Sander ***@***.***>:
