### ISSUE TITLE
WebSocket handshake error

### ISSUE THREAD

**Issue by Veldkornet** [Sholofly/ZiggoNext#69]
HomeAssistant 2021.4.5
Plug-in version 0.9.5
Started getting this issue today out of the blue when I restarted HomeAssistant:

```

2021-04-17 23:25:56 ERROR (MainThread) [homeassistant.setup] Error during setup of component ziggonext
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 242, in _async_setup_component
result = await task
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/ziggonext/__init__.py", line 30, in setup
api.connect()
File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 281, in connect
self.mqttClient.connect(self._mqtt_broker, DEFAULT_PORT)
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 941, in connect
return self.reconnect()
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1111, in reconnect
sock = WebsocketWrapper(sock, self._host, self._port, self._ssl,
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3580, in __init__
self._do_handshake(extra_headers)
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3664, in _do_handshake
raise WebsocketConnectionError("WebSocket handshake error")
paho.mqtt.client.WebsocketConnectionError: WebSocket handshake error
```

**Comment by Sholofly** [comment]
Hi @Veldkornet, There was a problem at the Ziggo end. I was developing this component and ran into the same issue :)

**Comment by Veldkornet** [comment]
Hmm yes, seems to be okay now! 😁
