### ISSUE TITLE
Mediaplayer stays on Videoland

### ISSUE THREAD

**Issue by silver323** [Sholofly/ZiggoNext#70]
Dear, 

Recently I noticed that the media player only shows the image from Videoland. So it no longer shows the actual channel which is currently on.
The sensor of the channel is also one that does not change and only remains on Videoland.
![image](https://user-images.githubusercontent.com/42837826/115450785-a53db200-a21c-11eb-9c1d-ab62d53a0bc4.png)
![image](https://user-images.githubusercontent.com/42837826/115450820-ae2e8380-a21c-11eb-9b07-37d9cf5c9c96.png)
All he indicates is whether the set-top box has been on or off in history.

**Comment by StevoNL** [comment]
Getting these type of crashes too. Also happens when viewing on demand / aflevering gemist. Got this out of the logs, always the same error: one expected two were given. Restarting Home Assistant fixes it for a while.

> 2021-04-27 21:19:43 ERROR (Thread-3) [ziggonext.ziggonext] Caught exception in on_message: box_update_callback() takes 1 positional argument but 2 were given
2021-04-27 21:19:43 ERROR (Thread-3) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3452, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2936, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3216, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3444, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 235, in _on_mqtt_client_message
    self.settop_boxes[deviceId].update_settopbox_state(jsonPayload)
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonextbox.py", line 82, in update_settopbox_state
    self._change_callback(self.box_id)
TypeError: box_update_callback() takes 1 positional argument but 2 were given

**Comment by Sholofly** [comment]
Have you updated the component? Looks like you use an old version.

**Comment by StevoNL** [comment]
> Have you updated the component? Looks like you use an old version.

>     "ziggonext==0.12.5"
>   ],
>   "dependencies": [],
>   "codeowners": ["@Sholofly"],
>   "version": "0.9.4"

**Comment by Sholofly** [comment]
Good to hear!

**Comment by TryhomeIT** [comment]
im having the same issue, after some time media player just shows playing and i cannot turn off or change channel.

**Comment by Sholofly** [comment]
@TryhomeIT Please update!

**Comment by StevoNL** [comment]
Thanks for the update Rudolf! Now only had a warning, not a crash.
2021-05-15 19:32:38 WARNING (Thread-5) [ziggonext.ziggonextbox] No channelId in stateSource. State update was skipped.

**Comment by Sholofly** [comment]
Thanks, thats expected behavior (for now).
