### ISSUE TITLE
Error on Component setup hassio core-2021.4.6

### ISSUE THREAD

**Issue by jordy101091** [Sholofly/ZiggoNext#71]
Logger: homeassistant.setup
Source: custom_components/ziggonext/__init__.py:30 
First occurred: 11:23:52 (1 occurrences) 
Last logged: 11:23:52

Error during setup of component ziggonext
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 242, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ziggonext/__init__.py", line 30, in setup
    api.connect()
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 282, in connect
    self._register_settop_boxes()
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 196, in _register_settop_boxes
    jsonResult = self._do_api_call(self._api_url_settop_boxes)
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 255, in _do_api_call
    return self._do_api_call(url, tries)
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 255, in _do_api_call
    return self._do_api_call(url, tries)
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 255, in _do_api_call
    return self._do_api_call(url, tries)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 243, in _do_api_call
    raise ZiggoNextConnectionError("API call failed. See previous errors.")
ziggonext.exceptions.ZiggoNextConnectionError: API call failed. See previous errors.

**Comment by Sholofly** [comment]
Hi Jordy, Can you give me more info about your config?

**Comment by Sholofly** [comment]
Stale, please reopen if you still experience some issues..
