### ISSUE TITLE
Error during setup

### ISSUE THREAD

**Issue by moostmartijn** [Sholofly/ZiggoNext#72]
Unfortunately the custom component stops working after a while. Most of the times after playback of a recording. Most of the time it works again after a restart of Home Assistant. Today it stopped working and I did a restart, but I keep getting this error:

```
Logger: homeassistant.setup
Source: custom_components/ziggonext/__init__.py:30
First occurred: 21:17:57 (1 occurrences)
Last logged: 21:17:57

Error during setup of component ziggonext
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 242, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ziggonext/__init__.py", line 30, in setup
    api.connect()
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 281, in connect
    self.mqttClient.connect(self._mqtt_broker, DEFAULT_PORT)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1111, in reconnect
    sock = WebsocketWrapper(sock, self._host, self._port, self._ssl,
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3580, in __init__
    self._do_handshake(extra_headers)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3623, in _do_handshake
    byte = self._socket.recv(1)
  File "/usr/local/lib/python3.8/ssl.py", line 1226, in recv
    return self.read(buflen)
  File "/usr/local/lib/python3.8/ssl.py", line 1101, in read
    return self._sslobj.read(len)
ConnectionResetError: [Errno 104] Connection reset by peer
```

The custom component won't setup unfortunately. Any ideas what could cause this error?

**Comment by Sholofly** [comment]
Can you connect to the box via the ziggogo.tv website?

Op di 4 mei 2021 21:22 schreef moostmartijn ***@***.***>:

**Comment by moostmartijn** [comment]
Yes, connecting to the box through ziggogo.tv works perfect!

**Comment by moostmartijn** [comment]
The custom component stopped working today and I checked if I could connect to the box through ziggogo.tv, but the connection button with the box name is grayed out, so I'm not able to connect. I also checked the (debug) logs of Home Assistant and I got this error:

```
2021-05-05 20:04:04 DEBUG (Thread-3) [ziggonext.ziggonext] Disconnected from mqtt client: 1
2021-05-05 20:04:38 DEBUG (Thread-3) [ziggonext.ziggonext] Disconnected from mqtt client: 1
2021-05-05 20:06:46 DEBUG (Thread-3) [ziggonext.ziggonext] Disconnected from mqtt client: 1
2021-05-05 20:08:05 DEBUG (Thread-3) [ziggonext.ziggonext] Not authorized mqtt client. Retry to connect
2021-05-05 20:08:11 DEBUG (Thread-3) [ziggonext.ziggonext] Disconnected from mqtt client: 5
2021-05-05 20:13:02 DEBUG (Thread-3) [ziggonext.ziggonext] Not authorized mqtt client. Retry to connect
2021-05-05 20:13:13 DEBUG (Thread-3) [ziggonext.ziggonext] Disconnected from mqtt client: 5
2021-05-05 20:15:14 DEBUG (Thread-3) [ziggonext.ziggonext] Not authorized mqtt client. Retry to connect
2021-05-05 20:15:14 DEBUG (Thread-3) [ziggonext.ziggonext] Disconnected from mqtt client: 5
2021-05-05 20:19:18 DEBUG (Thread-3) [ziggonext.ziggonext] Not authorized mqtt client. Retry to connect
2021-05-05 20:19:18 DEBUG (Thread-3) [ziggonext.ziggonext] Disconnected from mqtt client: 5
2021-05-05 20:23:53 DEBUG (Thread-3) [ziggonext.ziggonext] Not authorized mqtt client. Retry to connect
2021-05-05 20:23:53 DEBUG (Thread-3) [ziggonext.ziggonext] Disconnected from mqtt client: 5
2021-05-05 20:25:53 DEBUG (Thread-3) [ziggonext.ziggonext] Not authorized mqtt client. Retry to connect
2021-05-05 20:26:53 ERROR (Thread-3) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3452, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2942, in _packet_handle
    return self._handle_connack()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3029, in _handle_connack
    self.on_connect(
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 220, in _on_mqtt_client_connect
    client.connect(self._mqtt_broker, DEFAULT_PORT)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1111, in reconnect
    sock = WebsocketWrapper(sock, self._host, self._port, self._ssl,
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3580, in __init__
    self._do_handshake(extra_headers)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3623, in _do_handshake
    byte = self._socket.recv(1)
  File "/usr/local/lib/python3.8/ssl.py", line 1226, in recv
    return self.read(buflen)
  File "/usr/local/lib/python3.8/ssl.py", line 1101, in read
    return self._sslobj.read(len)
socket.timeout: The read operation timed out
```

**Comment by Sholofly** [comment]
Strange! Is it still not working? The first errors are all pointing to a connection problem between your box/HA and the Horizon servers.

**Comment by moostmartijn** [comment]
Unfortunately it still doesn't work. Sometimes it will work for some time after a restart, but most of the time it stops working the same day or the day after.

**Comment by Sholofly** [comment]
What type of box do you own?

**Comment by moostmartijn** [comment]
The Arris-DCX960-MPA+, but I must say that the last couple days everything works as it is supposed to do.

**Comment by Sholofly** [comment]
Sounds good! Please let me know if it keeps that way the coming days, so i can close this issue. Thanks in advance!

**Comment by masteriiz** [comment]
Hi. How do I give my password when it has spaces? don't know if that is the problem, but I get 'invaid credentials' when starting up, and I can connect to ziggo go. My password contains spaces, so I thought maybe that is the problem.

**Comment by Sholofly** [comment]
Was an Ziggo issue. Solved.
