### ISSUE TITLE
Uncaught thread exception at power on after vod or Netflix

### ISSUE THREAD

**Issue by digital-IMEI** [Sholofly/ZiggoNext#75]
Hi Rudolf,

I’m still facing issues after watching Netflix or using the playback function. 
after powering the box, the component crashes. 

```
Logger: root
Source: /usr/src/homeassistant/homeassistant/bootstrap.py:310
First occurred: 7:58:26 PM (1 occurrences) 
Last logged: 7:58:26 PM

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3452, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2936, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3216, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3444, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 238, in _on_mqtt_client_message
    self.settop_boxes[deviceId].update_settop_box(jsonPayload)
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonextbox.py", line 173, in update_settop_box
    if stateSource == "None" or not "channelId" in stateSource:
TypeError: argument of type 'NoneType' is not iterable
```

any advice? I’m on  the latest version. 

```
{
  "domain": "ziggonext",
  "name": "Ziggo Next",
  "documentation": "",
  "requirements": [
    "ziggonext==0.12.5"
  ],
  "dependencies": [],
  "codeowners": ["@Sholofly"],
  "version": "0.9.4"
}
```

**Comment by Sholofly** [comment]
Please update to the latest version . I added some fallbacks when the information is not complete, or at least different from what I expect.

**Comment by digital-IMEI** [comment]
I've updated the component (manifest file). I don't know what you've done but i'm not able to reproduce the issue anymore. 🙌

I'll report back if it happens again. Thx!

**Comment by digital-IMEI** [comment]
Hi,

just a quick update, no issues so far anymore 🙌
