### ISSUE TITLE
API call failed: 410

### ISSUE THREAD

**Issue by Veldkornet** [Sholofly/ZiggoNext#80]
Recently I started getting the error below when HomeAssistant starts, any idea?

```
2021-05-25 14:01:38 ERROR (MainThread) [homeassistant.setup] Error during setup of component ziggonext
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 248, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ziggonext/__init__.py", line 32, in setup
    api.connect()
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 276, in connect
    self.get_session_and_token()
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 59, in get_session_and_token
    self._get_token()
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 269, in _get_token
    jsonResult = self._do_api_call(self._api_url_token) 
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 265, in _do_api_call
    raise ZiggoNextConnectionError("API call failed: " + str(response.status_code))
ziggonext.exceptions.ZiggoNextConnectionError: API call failed: 410
```

Does API code 410 = [HTTP Code 410](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/410) ?

**Comment by bramstroker** [comment]
I have this same error since last update

**Comment by Sholofly** [comment]
Hey guys, I have te same issue. Nothing to do with the update though, it's a change on the Ziggo side of life ;) I'll look into it ASAP!

**Comment by paulgottgens** [comment]
Hi Rudolf. Ziggo Next stopte er mee na de laatste update naar 0.10.0. Maar ik zie dat er al meer mensen hetzelfde probleem hebben. Ik ben helaas geen programmeur, dus ik kan helemaal niks met de logs.
Hopelijk kun je het snel oplossen, want ik vind de addon helemaal top.

Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant.setup
Source: custom_components/ziggonext/__init__.py:32
Integration: ziggonext (documentation)
First occurred: 17:47:24 (1 occurrences)
Last logged: 17:47:24

Error during setup of component ziggonext
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 248, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ziggonext/__init__.py", line 32, in setup
    api.connect()
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 276, in connect
    self.get_session_and_token()
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 59, in get_session_and_token
    self._get_token()
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 269, in _get_token
    jsonResult = self._do_api_call(self._api_url_token)
  File "/usr/local/lib/python3.8/site-packages/ziggonext/ziggonext.py", line 265, in _do_api_call
    raise ZiggoNextConnectionError("API call failed: " + str(response.status_code))
ziggonext.exceptions.ZiggoNextConnectionError: API call failed: 410

**Comment by Sholofly** [comment]
Hi guys, Can you reinstall the component, and tell me your findings? I hadn't update my component myself and after the update it was working again. Can't reproduce the issue anymore...

**Comment by ookonbekend** [comment]
Hello,
After a restart it's working again, I'm sure it was related to the Ziggo network, in the Ziggo Go Apps (Windows and IOS) the mediabox wasn't available either.

Keep up the good work, many thanks!

**Comment by bramstroker** [comment]
Yes also working for me again. Glad Ziggo didn't change the API. Keep up the great work Rudolf!

**Comment by paulgottgens** [comment]
Yep, it is working again after the reboot. Thanks!!
