### ISSUE TITLE
TypeError: sequence item 0: expected str instance, Optional found

### ISSUE THREAD

**Issue by AndyVRD** [Sholofly/ZiggoNext#85]
Hi,

First of all thanks for the integration. Just installed it for the Telenet TVBOX, i can see my state is playing and also recordings are showing. The problem is that i can't change to on/off and the state only change if i restart HA. I'm sure my credentials (username/password) are correct. Have already un-installed the integration, restarted the tvbox but still same problem. If i try to switch the tvbox on or off i get the following error in my logs.

`Source: helpers/config_validation.py:134
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 15:22:08 (3 occurrences)
Last logged: 15:22:17

[547914134480] sequence item 0: expected str instance, Optional found
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1445, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 215, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 339, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/src/homeassistant/homeassistant/helpers/config_validation.py", line 134, in validate
    raise vol.Invalid("must contain at least one of {}.".format(", ".join(keys)))
TypeError: sequence item 0: expected str instance, Optional found`

**Comment by AndyVRD** [comment]
@Sholofly I have found the problem but no idea how we can fix it, is there any change you can contact me and we can troubleshoot. :)
